/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process is up */
        get: operations["livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Can this instance serve traffic? */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full diagnostics with fixes */
        get: operations["diagnostics_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test settings before saving
         * @description Used by the first-run wizard: proves the model, key and search backend actually work.
         */
        post: operations["setup_test_setup_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a question
         * @description Returns immediately. Open `stream_url` (Server-Sent Events) to receive the answer. Re-connect with `Last-Event-ID` to resume without losing events.
         */
        post: operations["submit_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream a query's events (SSE) */
        get: operations["stream_stream__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query status */
        get: operations["status_queries__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop generating */
        post: operations["cancel_queries__query_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documentation of SSE event payloads
         * @description Returns an empty catalog; exists so client generators see every event schema.
         */
        get: operations["event_catalog_schema_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations */
        get: operations["list_threads_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a conversation */
        get: operations["get_thread_threads__thread_id__get"];
        put?: never;
        post?: never;
        /** Delete a conversation */
        delete: operations["delete_thread_threads__thread_id__delete"];
        options?: never;
        head?: never;
        /** Rename or pin */
        patch: operations["update_thread_threads__thread_id__patch"];
        trace?: never;
    };
    "/threads/{thread_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one answer */
        delete: operations["delete_message_threads__thread_id__messages__message_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{thread_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a conversation as Markdown or PDF */
        get: operations["export_thread_threads__thread_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web search (no LLM) */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch and clean one page */
        post: operations["fetch_page_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passages from the local index */
        post: operations["retrieve_passages_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proxy/favicon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Privacy-preserving favicon (fetched server-side) */
        get: operations["favicon_proxy_favicon_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proxy/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a remote image server-side so the browser never contacts the origin
         * @description Answers can embed images, and a prompt-injected page could point one at an attacker's server
         *     to leak data in the URL. Routing every image through here (SSRF-guarded, raster types only,
         *     size-capped) removes both the tracking and the exfiltration channel.
         */
        get: operations["proxy_image_proxy_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current settings (secrets redacted) */
        get: operations["get_settings_settings_get"];
        /** Update settings */
        put: operations["put_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/clear-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forget cached pages and embeddings */
        post: operations["clear_cache_data_clear_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete all conversations, feedback and traces */
        post: operations["wipe_data_wipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thumbs up/down on an answer */
        post: operations["feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_operator_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent query traces (no raw queries) */
        get: operations["list_traces_operator_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["prometheus_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privacy/egress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent outbound connections */
        get: operations["egress_activity_privacy_egress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privacy/egress/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the egress log */
        post: operations["clear_egress_privacy_egress_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privacy/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Privacy feature flags currently in effect */
        get: operations["privacy_status_privacy_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List model ids */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat completion with web search and citations */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerCompleteEvent */
        AnswerCompleteEvent: {
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** AnswerDeltaEvent */
        AnswerDeltaEvent: {
            /** Text */
            text: string;
            /**
             * Draft
             * @default false
             */
            draft: boolean;
        };
        /**
         * AnswerUpgradeEvent
         * @description The draft answer is being replaced by one written from full pages. Clear and re-stream.
         */
        AnswerUpgradeEvent: {
            /**
             * Reason
             * @default full_pages
             */
            reason: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant" | "developer" | "tool";
            /** Content */
            content?: string | {
                [key: string]: unknown;
            }[] | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Model
             * @default gleanwise-quick
             */
            model: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Stream Options */
            stream_options?: {
                [key: string]: unknown;
            } | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** User */
            user?: string | null;
        };
        /** Citation */
        Citation: {
            /** Number */
            number: number;
            /** Source Id */
            source_id?: number | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
        };
        /**
         * DataFlowInfo
         * @description Per-answer data-flow summary (D11). Built from request + settings, no extra egress.
         */
        DataFlowInfo: {
            /**
             * Search
             * @default true
             */
            search: boolean;
            /**
             * Pages Fetched
             * @default 0
             */
            pages_fetched: number;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Model Local
             * @default false
             */
            model_local: boolean;
            /**
             * Redaction
             * @default false
             */
            redaction: boolean;
            /**
             * Private
             * @default false
             */
            private: boolean;
            /**
             * Proxy
             * @default false
             */
            proxy: boolean;
            /**
             * Socks5
             * @default false
             */
            socks5: boolean;
            /**
             * Strict Local
             * @default false
             */
            strict_local: boolean;
        };
        /** DoneEvent */
        DoneEvent: {
            /** Query Id */
            query_id: string;
            /** Thread Id */
            thread_id: string;
            /** Message Id */
            message_id: string | null;
            /**
             * Status
             * @default complete
             * @enum {string}
             */
            status: "complete" | "cancelled";
            /**
             * Answer
             * @default
             */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Follow Ups */
            follow_ups: string[];
            usage: components["schemas"]["UsageInfo"];
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Research Summary */
            research_summary: string | null;
            data_flow: components["schemas"]["DataFlowInfo"] | null;
        };
        /** EgressActivity */
        EgressActivity: {
            /**
             * Gateway
             * @default
             */
            gateway: string;
            /**
             * Gateway Status
             * @default
             */
            gateway_status: string;
            /** Entries */
            entries?: components["schemas"]["EgressEvent"][];
        };
        /** EgressEvent */
        EgressEvent: {
            /** Ts */
            ts: number;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Purpose */
            purpose: string;
            /**
             * Bytes In
             * @default 0
             */
            bytes_in: number;
            /**
             * Bytes Out
             * @default 0
             */
            bytes_out: number;
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Hint */
            hint?: string | null;
            /** Action */
            action?: string | null;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /**
         * EventCatalog
         * @description Union of every event a query stream can emit, keyed by SSE ``event:`` name.
         */
        EventCatalog: {
            plan?: components["schemas"]["PlanEvent"] | null;
            sources?: components["schemas"]["SourcesEvent"] | null;
            source_update?: components["schemas"]["SourceUpdateEvent"] | null;
            answer_delta?: components["schemas"]["AnswerDeltaEvent"] | null;
            answer_upgrade?: components["schemas"]["AnswerUpgradeEvent"] | null;
            answer_complete?: components["schemas"]["AnswerCompleteEvent"] | null;
            follow_ups?: components["schemas"]["FollowUpsEvent"] | null;
            reasoning_delta?: components["schemas"]["ReasoningDeltaEvent"] | null;
            visit?: components["schemas"]["VisitEvent"] | null;
            warning?: components["schemas"]["WarningEvent"] | null;
            done?: components["schemas"]["DoneEvent"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Query Id */
            query_id: string;
            /** Thumb */
            thumb: number;
            /** Comment */
            comment?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Query Id */
            query_id: string;
            /** Thumb */
            thumb: number;
            /** Comment */
            comment?: string | null;
        };
        /** FetchRequest */
        FetchRequest: {
            /** Url */
            url: string;
            /**
             * Max Chars
             * @default 20000
             */
            max_chars: number;
        };
        /** FetchResponse */
        FetchResponse: {
            /** Url */
            url: string;
            /** Final Url */
            final_url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Text */
            text: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
        };
        /**
         * Focus
         * @enum {string}
         */
        Focus: "general" | "academic" | "news" | "social";
        /** FollowUpsEvent */
        FollowUpsEvent: {
            /** Questions */
            questions: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthComponent */
        HealthComponent: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Hint */
            hint?: string | null;
            /** Action */
            action?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Components */
            components: components["schemas"]["HealthComponent"][];
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            mode?: components["schemas"]["Mode"] | null;
            focus?: components["schemas"]["Focus"] | null;
            /** Sources */
            sources?: components["schemas"]["Source"][];
            /** Created At */
            created_at?: string | null;
            /** Query Id */
            query_id?: string | null;
            /** Research Summary */
            research_summary?: string | null;
            /** Research Log */
            research_log?: {
                [key: string]: unknown;
            }[] | null;
            /** Follow Ups */
            follow_ups?: string[];
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "quick" | "pro" | "deep";
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** PlanEvent */
        PlanEvent: {
            /** Steps */
            steps: string[];
            mode: components["schemas"]["Mode"];
            /** Rewritten Query */
            rewritten_query: string | null;
            /** Subqueries */
            subqueries: string[];
        };
        /** QueryAccepted */
        QueryAccepted: {
            /** Query Id */
            query_id: string;
            /** Thread Id */
            thread_id: string;
            /** Stream Url */
            stream_url: string;
        };
        /**
         * QueryRequest
         * @example {
         *       "query": "How do heat pumps work?"
         *     }
         */
        QueryRequest: {
            /** Query */
            query: string;
            /** Thread Id */
            thread_id?: string | null;
            /** @default quick */
            mode: components["schemas"]["Mode"];
            /** @default general */
            focus: components["schemas"]["Focus"];
            /** Model */
            model?: string | null;
            /** Locale */
            locale?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** History */
            history?: components["schemas"]["Turn"][] | null;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
            /**
             * Private
             * @default false
             */
            private: boolean;
            /**
             * Draft
             * @default true
             */
            draft: boolean;
            /** Regenerate Message Id */
            regenerate_message_id?: string | null;
        };
        /** QueryStatus */
        QueryStatus: {
            /** Query Id */
            query_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "complete" | "error" | "cancelled";
            mode: components["schemas"]["Mode"];
            /**
             * Last Event Id
             * @default 0
             */
            last_event_id: number;
        };
        /** ReasoningDeltaEvent */
        ReasoningDeltaEvent: {
            /** Text */
            text: string;
            /** Round */
            round: number | null;
        };
        /** RetrieveRequest */
        RetrieveRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
            /** Urls */
            urls?: string[] | null;
        };
        /** RetrieveResponse */
        RetrieveResponse: {
            /** Query */
            query: string;
            /** Chunks */
            chunks: components["schemas"]["RetrievedChunk"][];
        };
        /** RetrievedChunk */
        RetrievedChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Heading Path
             * @default
             */
            heading_path: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /** @default general */
            focus: components["schemas"]["Focus"];
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Locale */
            locale?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["Source"][];
            /** Warnings */
            warnings?: string[];
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
            /** Llm Api Base */
            llm_api_base?: string | null;
            /** Embedder */
            embedder?: ("local" | "litellm" | "hash") | null;
            /** Embed Model */
            embed_model?: string | null;
            /** Searxng Url */
            searxng_url?: string | null;
            /** Thread Retention Days */
            thread_retention_days?: number | null;
            /** Webhook Url */
            webhook_url?: string | null;
            /** Locale */
            locale?: string | null;
            /** Strict Local */
            strict_local?: boolean | null;
            /** Redact Pii */
            redact_pii?: boolean | null;
            /** Egress Gateway */
            egress_gateway?: boolean | null;
            /** Socks5 Url */
            socks5_url?: string | null;
            /** Socks5 For Search */
            socks5_for_search?: boolean | null;
            /** Socks5 For Fetch */
            socks5_for_fetch?: boolean | null;
            /** Local Hosts */
            local_hosts?: string[] | null;
            /** Operator Metrics */
            operator_metrics?: boolean | null;
            /** Operator Webhooks */
            operator_webhooks?: boolean | null;
        };
        /**
         * SettingsView
         * @description Redacted settings for the browser. Secrets are reported only as ``*_set`` booleans.
         */
        SettingsView: {
            /**
             * Llm Model
             * @default
             */
            llm_model: string;
            /**
             * Llm Api Base
             * @default
             */
            llm_api_base: string;
            /**
             * Llm Api Key Set
             * @default false
             */
            llm_api_key_set: boolean;
            /**
             * Embedder
             * @default local
             */
            embedder: string;
            /**
             * Embed Model
             * @default
             */
            embed_model: string;
            /**
             * Searxng Url
             * @default
             */
            searxng_url: string;
            /**
             * Thread Retention Days
             * @default 28
             */
            thread_retention_days: number;
            /**
             * Webhook Url
             * @default
             */
            webhook_url: string;
            /**
             * Locale
             * @default
             */
            locale: string;
            /**
             * Profile
             * @default local
             */
            profile: string;
            /**
             * Configured
             * @default false
             */
            configured: boolean;
            /**
             * Auth Required
             * @default false
             */
            auth_required: boolean;
            /** Env Locked */
            env_locked?: string[];
            /**
             * Version
             * @default
             */
            version: string;
            /**
             * Strict Local
             * @default false
             */
            strict_local: boolean;
            /**
             * Llm Local
             * @default false
             */
            llm_local: boolean;
            /**
             * Redact Pii
             * @default false
             */
            redact_pii: boolean;
            /**
             * Egress Gateway
             * @default true
             */
            egress_gateway: boolean;
            /**
             * Egress Proxy Url
             * @default
             */
            egress_proxy_url: string;
            /**
             * Socks5 Url
             * @default
             */
            socks5_url: string;
            /**
             * Socks5 For Search
             * @default false
             */
            socks5_for_search: boolean;
            /**
             * Socks5 For Fetch
             * @default false
             */
            socks5_for_fetch: boolean;
            /** Local Hosts */
            local_hosts?: string[];
            /**
             * Operator Metrics
             * @default false
             */
            operator_metrics: boolean;
            /**
             * Operator Webhooks
             * @default false
             */
            operator_webhooks: boolean;
            /**
             * Keychain Available
             * @default false
             */
            keychain_available: boolean;
        };
        /** SetupTestRequest */
        SetupTestRequest: {
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
            /** Llm Api Base */
            llm_api_base?: string | null;
            /** Searxng Url */
            searxng_url?: string | null;
        };
        /** SetupTestResult */
        SetupTestResult: {
            llm: components["schemas"]["HealthComponent"];
            search: components["schemas"]["HealthComponent"];
            embeddings: components["schemas"]["HealthComponent"];
        };
        /** Source */
        Source: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /**
             * Domain
             * @default
             */
            domain: string;
            /** Favicon */
            favicon?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Engines */
            engines?: string[];
            /**
             * Used In Answer
             * @default false
             */
            used_in_answer: boolean;
            /**
             * State
             * @default found
             * @enum {string}
             */
            state: "found" | "reading" | "read" | "failed" | "skipped";
        };
        /** SourceUpdateEvent */
        SourceUpdateEvent: {
            /** Id */
            id: number;
            /**
             * State
             * @enum {string}
             */
            state: "found" | "reading" | "read" | "failed" | "skipped";
            /** Reason */
            reason: string | null;
        };
        /** SourcesEvent */
        SourcesEvent: {
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** ThreadDetail */
        ThreadDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /** ThreadSummary */
        ThreadSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            mode?: components["schemas"]["Mode"] | null;
        };
        /** ThreadUpdate */
        ThreadUpdate: {
            /** Title */
            title?: string | null;
            /** Pinned */
            pinned?: boolean | null;
        };
        /** Turn */
        Turn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** UsageInfo */
        UsageInfo: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /** Cost Usd */
            cost_usd: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitEvent */
        VisitEvent: {
            /** Source Id */
            source_id: number;
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Round */
            round: number | null;
        };
        /** WarningEvent */
        WarningEvent: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    diagnostics_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    setup_test_setup_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_stream__query_id__get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream. See `GET /schema/events` for payload shapes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_queries__query_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_queries__query_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_catalog_schema_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCatalog"];
                };
            };
        };
    };
    list_threads_threads_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thread_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_threads__thread_id__messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_thread_threads__thread_id__export_get: {
        parameters: {
            query?: {
                format?: "md" | "pdf";
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_page_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_passages_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favicon_proxy_favicon_get: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_image_proxy_image_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
        };
    };
    put_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_data_clear_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    wipe_data_wipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_operator_feedback_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_operator_traces_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prometheus_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    egress_activity_privacy_egress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressActivity"];
                };
            };
        };
    };
    clear_egress_privacy_egress_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    privacy_status_privacy_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
