# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Ved Buddaraju

"""Storage contract. Every backend (SQLite, Postgres) implements this async interface."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

import numpy as np

from gleanwise.models import (
    Chunk,
    Document,
    FeedbackOut,
    MessageOut,
    ThreadDetail,
    ThreadSummary,
    Turn,
)

Scored = tuple[Chunk, float]


class Store(Protocol):
    backend: str

    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def ping(self) -> dict[str, Any]: ...
    async def stats(self) -> dict[str, int]: ...

    # documents & chunks --------------------------------------------------------------------
    async def get_document(self, canonical_url: str) -> Document | None: ...
    async def put_document(self, doc: Document) -> None: ...
    async def touch_document(
        self, doc_id: str, fetched_at: datetime, expires_at: datetime
    ) -> None: ...
    async def get_documents(self, doc_ids: list[str]) -> dict[str, Document]: ...
    async def chunk_count(self, doc_id: str) -> int: ...
    async def replace_chunks(self, doc_id: str, chunks: list[Chunk]) -> None: ...
    async def lead_chunks(self, doc_ids: list[str], per_doc: int) -> list[Chunk]: ...
    async def chunks_needing_vectors(self, doc_ids: list[str], model: str) -> list[Chunk]: ...
    async def set_vectors(self, chunk_ids: list[str], vectors: np.ndarray, model: str) -> None: ...
    async def bm25(self, query: str, limit: int, doc_ids: list[str] | None) -> list[Scored]: ...
    async def dense(
        self, vector: np.ndarray, limit: int, doc_ids: list[str] | None, model: str
    ) -> list[Scored]: ...
    async def clear_index(self) -> None: ...

    # threads & messages --------------------------------------------------------------------
    async def create_thread(self, title: str) -> ThreadSummary: ...
    async def get_thread(self, thread_id: str) -> ThreadDetail | None: ...
    async def list_threads(self, q: str | None, limit: int, offset: int) -> list[ThreadSummary]: ...
    async def update_thread(
        self, thread_id: str, title: str | None, pinned: bool | None
    ) -> bool: ...
    async def delete_thread(self, thread_id: str) -> bool: ...
    async def add_turn(
        self, thread_id: str, user: dict[str, Any], assistant: dict[str, Any]
    ) -> MessageOut: ...
    async def history(self, thread_id: str, limit: int) -> list[Turn]: ...
    async def delete_message(self, message_id: str) -> bool: ...
    async def purge_threads(self, older_than_days: int) -> int: ...
    async def wipe_user_data(self) -> None: ...

    # feedback & traces ---------------------------------------------------------------------
    async def add_feedback(self, query_id: str, thumb: int, comment: str | None) -> None: ...
    async def list_feedback(self, limit: int) -> list[FeedbackOut]: ...
    async def add_trace(
        self, query_id: str, thread_id: str | None, payload: dict[str, Any]
    ) -> None: ...
    async def list_traces(self, limit: int) -> list[dict[str, Any]]: ...
    async def purge_traces(self, older_than_days: int) -> int: ...
